name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  project:
    required: true
    description: Pulumi project to check
  working-directory:
    description: Working directory of your Pulumi project
    default: '.'
  legacy-tags:
    required: true
    description: Tags spec to check for legacy stacks
  timeout-hours:
    required: true
    description: The number of hours since the last update after which a stack should be destroyed
  preview:
    required: false
    description: When set to true, logs what what the action would do but doesn\'t destroy and stacks
  verbose:
    required: false
    description: Outputs detailed logs regarding the checks for each stack
runs:
  using: 'node16'
  main: 'dist/index.js'
